flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- container-1.0.1
- data-construction-1.0
- data-layer-1.0.3
- functor-utils-1.0
- lens-utils-1.0
- typelevel-1.0.2
- doctest-discover-0.1.0.7
resolver: lts-3.11
